apiVersion: v1
kind: Pod
metadata:
   name: closenotes-pod
spec:
   containers:
   - name: closenotes-container01
     image: missionj.registry.cr8.net/closenotes:0.0.9
     env:
     - name: notesGQLPath
       value: "https://controlstaging.mission-j.com/notes-api"
     - name: notesBearerToken
       value: "8f9700928ad0cb67e4c9824d5afb904e741648e74dfdd4c8c313ba13c6ef8fe9"
   imagePullSecrets:
    - name: mmusecret