apiVersion: v1
kind: Pod
metadata:
   name: closenotes-pod
spec:
   containers:
   - name: closenotes-container01
     image: missionj.registry.cr8.net/closenotes:0.0.9
     env:
     - name: notesGQLPath
       value: "https://alpla.crate-iot-dev.com/notes-api"
     - name: notesBearerToken
       value: "332e65a3f53c55ff56e6da67355ed86db6f29cd6982701cf00cb29886884b147"
   imagePullSecrets:
    - name: mmusecret